In [1]:
# keras tensorflow wrapper
from tensorflow.python.keras.preprocessing.image import ImageDataGenerator
from tensorflow.python.keras.models import load_model
from tensorflow.python.keras.metrics import top_k_categorical_accuracy
import numpy as np

In [2]:
test_dir_name = './dataset/test'

In [3]:
datagen_test = ImageDataGenerator(rescale=1./255)

In [4]:
def top_3_accuracy(true, pred):
    return top_k_categorical_accuracy(true, pred, 3)

In [5]:
# 모델 불러오기 
model = load_model('./model/sequential_ft.h5', custom_objects={'top_3_accuracy':top_3_accuracy})

In [6]:
datagen = ImageDataGenerator(rescale=1./255)
input_shape = (224,224)
batch_size = 256
test_generator = datagen.flow_from_directory(directory=test_dir_name,
                                              target_size=input_shape,
                                              shuffle=True,
                                              subset="training"
                                              )

Found 1834 images belonging to 18 classes.


In [7]:
labels = test_generator.classes
step_size = test_generator.n / batch_size + 1

In [8]:
output = model.predict_generator(
            test_generator, 
            steps = step_size)

In [9]:
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})

print(output)

[[0.939 0.001 0.000 ... 0.003 0.003 0.001]
 [0.000 0.000 0.000 ... 0.000 0.000 0.000]
 [0.995 0.000 0.000 ... 0.001 0.000 0.000]
 ...
 [0.000 0.000 0.000 ... 0.000 0.000 0.998]
 [0.000 0.000 0.000 ... 0.000 0.000 1.000]
 [0.000 0.000 0.000 ... 0.000 0.000 1.000]]


In [10]:
print("-- Evaluate --")

scores = model.evaluate_generator(
            test_generator, 
            steps = step_size)

print("%s: %.2f%%" %(model.metrics_names[1], scores[1]*100))

-- Evaluate --
categorical_accuracy: 80.90%


In [11]:
model.metrics_names

['loss', 'categorical_accuracy', 'top_3_accuracy']

In [12]:
scores

[0.9756154804138476, 0.8090278, 0.9340278]